#!/bin/bash

wget "https://dax-cdn.cdn.appdomain.cloud/dax-fashion-mnist/1.0.2/fashion-mnist.tar.gz"
tar -xzvf fashion-mnist.tar.gz && rm LICENSE.txt fashion-mnist_test.csv && mv fashion-mnist_train.csv all_data.csv
rm fashion-mnist.tar.gz
python3 partition.py
