# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from scaleoututil.grpc import scaleout_pb2 as scaleoututil_dot_grpc_dot_scaleout__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in scaleoututil/grpc/scaleout_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CombinerClientStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendModelUpdate = channel.unary_unary(
                '/scaleout.CombinerClient/SendModelUpdate',
                request_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.ModelUpdate.SerializeToString,
                response_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
                _registered_method=True)
        self.SendModelValidation = channel.unary_unary(
                '/scaleout.CombinerClient/SendModelValidation',
                request_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.ModelValidation.SerializeToString,
                response_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
                _registered_method=True)
        self.SendModelPrediction = channel.unary_unary(
                '/scaleout.CombinerClient/SendModelPrediction',
                request_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.ModelPrediction.SerializeToString,
                response_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
                _registered_method=True)
        self.SendBackwardCompletion = channel.unary_unary(
                '/scaleout.CombinerClient/SendBackwardCompletion',
                request_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.BackwardCompletion.SerializeToString,
                response_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
                _registered_method=True)
        self.SendModelMetric = channel.unary_unary(
                '/scaleout.CombinerClient/SendModelMetric',
                request_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.ModelMetric.SerializeToString,
                response_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
                _registered_method=True)
        self.SendAttributeMessage = channel.unary_unary(
                '/scaleout.CombinerClient/SendAttributeMessage',
                request_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.AttributeMessage.SerializeToString,
                response_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
                _registered_method=True)
        self.SendTelemetryMessage = channel.unary_unary(
                '/scaleout.CombinerClient/SendTelemetryMessage',
                request_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.TelemetryMessage.SerializeToString,
                response_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
                _registered_method=True)
        self.Announce = channel.unary_unary(
                '/scaleout.CombinerClient/Announce',
                request_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.ClientAnnounceRequest.SerializeToString,
                response_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
                _registered_method=True)
        self.PollAndReport = channel.unary_unary(
                '/scaleout.CombinerClient/PollAndReport',
                request_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.ActivityReport.SerializeToString,
                response_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.TaskRequest.FromString,
                _registered_method=True)
        self.SendStatus = channel.unary_unary(
                '/scaleout.CombinerClient/SendStatus',
                request_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Status.SerializeToString,
                response_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/scaleout.CombinerClient/SendHeartbeat',
                request_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Heartbeat.SerializeToString,
                response_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
                _registered_method=True)
        self.TaskStream = channel.unary_stream(
                '/scaleout.CombinerClient/TaskStream',
                request_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.ClientAvailableMessage.SerializeToString,
                response_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.TaskRequest.FromString,
                _registered_method=True)


class CombinerClientServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendModelUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendModelValidation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendModelPrediction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendBackwardCompletion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendModelMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAttributeMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTelemetryMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Announce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollAndReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendStatus(self, request, context):
        """Status endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Client messaging to stay engaged.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskStream(self, request, context):
        """Stream endpoints for training/validation pub/sub
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CombinerClientServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendModelUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendModelUpdate,
                    request_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.ModelUpdate.FromString,
                    response_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.SerializeToString,
            ),
            'SendModelValidation': grpc.unary_unary_rpc_method_handler(
                    servicer.SendModelValidation,
                    request_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.ModelValidation.FromString,
                    response_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.SerializeToString,
            ),
            'SendModelPrediction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendModelPrediction,
                    request_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.ModelPrediction.FromString,
                    response_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.SerializeToString,
            ),
            'SendBackwardCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBackwardCompletion,
                    request_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.BackwardCompletion.FromString,
                    response_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.SerializeToString,
            ),
            'SendModelMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.SendModelMetric,
                    request_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.ModelMetric.FromString,
                    response_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.SerializeToString,
            ),
            'SendAttributeMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAttributeMessage,
                    request_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.AttributeMessage.FromString,
                    response_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.SerializeToString,
            ),
            'SendTelemetryMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTelemetryMessage,
                    request_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.TelemetryMessage.FromString,
                    response_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.SerializeToString,
            ),
            'Announce': grpc.unary_unary_rpc_method_handler(
                    servicer.Announce,
                    request_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.ClientAnnounceRequest.FromString,
                    response_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.SerializeToString,
            ),
            'PollAndReport': grpc.unary_unary_rpc_method_handler(
                    servicer.PollAndReport,
                    request_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.ActivityReport.FromString,
                    response_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.TaskRequest.SerializeToString,
            ),
            'SendStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SendStatus,
                    request_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Status.FromString,
                    response_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Heartbeat.FromString,
                    response_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.Response.SerializeToString,
            ),
            'TaskStream': grpc.unary_stream_rpc_method_handler(
                    servicer.TaskStream,
                    request_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.ClientAvailableMessage.FromString,
                    response_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.TaskRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scaleout.CombinerClient', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scaleout.CombinerClient', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CombinerClient(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendModelUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scaleout.CombinerClient/SendModelUpdate',
            scaleoututil_dot_grpc_dot_scaleout__pb2.ModelUpdate.SerializeToString,
            scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendModelValidation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scaleout.CombinerClient/SendModelValidation',
            scaleoututil_dot_grpc_dot_scaleout__pb2.ModelValidation.SerializeToString,
            scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendModelPrediction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scaleout.CombinerClient/SendModelPrediction',
            scaleoututil_dot_grpc_dot_scaleout__pb2.ModelPrediction.SerializeToString,
            scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendBackwardCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scaleout.CombinerClient/SendBackwardCompletion',
            scaleoututil_dot_grpc_dot_scaleout__pb2.BackwardCompletion.SerializeToString,
            scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendModelMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scaleout.CombinerClient/SendModelMetric',
            scaleoututil_dot_grpc_dot_scaleout__pb2.ModelMetric.SerializeToString,
            scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendAttributeMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scaleout.CombinerClient/SendAttributeMessage',
            scaleoututil_dot_grpc_dot_scaleout__pb2.AttributeMessage.SerializeToString,
            scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTelemetryMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scaleout.CombinerClient/SendTelemetryMessage',
            scaleoututil_dot_grpc_dot_scaleout__pb2.TelemetryMessage.SerializeToString,
            scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Announce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scaleout.CombinerClient/Announce',
            scaleoututil_dot_grpc_dot_scaleout__pb2.ClientAnnounceRequest.SerializeToString,
            scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollAndReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scaleout.CombinerClient/PollAndReport',
            scaleoututil_dot_grpc_dot_scaleout__pb2.ActivityReport.SerializeToString,
            scaleoututil_dot_grpc_dot_scaleout__pb2.TaskRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scaleout.CombinerClient/SendStatus',
            scaleoututil_dot_grpc_dot_scaleout__pb2.Status.SerializeToString,
            scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scaleout.CombinerClient/SendHeartbeat',
            scaleoututil_dot_grpc_dot_scaleout__pb2.Heartbeat.SerializeToString,
            scaleoututil_dot_grpc_dot_scaleout__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TaskStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scaleout.CombinerClient/TaskStream',
            scaleoututil_dot_grpc_dot_scaleout__pb2.ClientAvailableMessage.SerializeToString,
            scaleoututil_dot_grpc_dot_scaleout__pb2.TaskRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upload = channel.stream_unary(
                '/scaleout.ModelService/Upload',
                request_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.FileChunk.SerializeToString,
                response_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.ModelResponse.FromString,
                _registered_method=True)
        self.Download = channel.unary_stream(
                '/scaleout.ModelService/Download',
                request_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.ModelRequest.SerializeToString,
                response_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.FileChunk.FromString,
                _registered_method=True)


class ModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Upload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upload': grpc.stream_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.FileChunk.FromString,
                    response_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.ModelResponse.SerializeToString,
            ),
            'Download': grpc.unary_stream_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=scaleoututil_dot_grpc_dot_scaleout__pb2.ModelRequest.FromString,
                    response_serializer=scaleoututil_dot_grpc_dot_scaleout__pb2.FileChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scaleout.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scaleout.ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/scaleout.ModelService/Upload',
            scaleoututil_dot_grpc_dot_scaleout__pb2.FileChunk.SerializeToString,
            scaleoututil_dot_grpc_dot_scaleout__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scaleout.ModelService/Download',
            scaleoututil_dot_grpc_dot_scaleout__pb2.ModelRequest.SerializeToString,
            scaleoututil_dot_grpc_dot_scaleout__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
