# Label pull requests based on file paths, titles, or branch names
docs:
- changed-files:
  - any-glob-to-any-file: ['docs/**','**/*.md']

feature:
  - head-branch: ['^feature', 'feature']

fix:
  - head-branch: ['^bug', 'bug', '^fix', 'fix']