version: '3.3'
services:
  client:
    environment:
      - GET_HOSTS_FROM=dns
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/
    command: /bin/bash -c "fedn run client -in ./config/settings-client.yaml"
    volumes:
      - ./config:/app/config
      - ./test/${EXAMPLE}/data:/app/data
