version: '3.7'

services:

  client1:
    environment:
      - GET_HOSTS_FROM=dns
      - CLIENT_NAME=${CLIENT_NAME_BASE}1
      - FEDN_MINIO_HOST=${FEDN_MINIO_HOST}
      - FEDN_MINIO_PORT=${FEDN_MINIO_PORT}
      - FEDN_MINIO_ACCESS_KEY=${FEDN_MINIO_ACCESS_KEY}
      - FEDN_MINIO_SECRET_KEY=${FEDN_MINIO_SECRET_KEY}
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/
    command: /bin/bash -c "fedn run client -d ${FEDN_REDUCER_HOST} -p ${FEDN_REDUCER_PORT} -n ${CLIENT_NAME_BASE}1  -t ${FEDN_ALLIANCE_ADMIN_AUTH_TOKEN}"
    volumes:
      - ./test/${EXAMPLE}/data/data1:/app/data
      - ./test/${EXAMPLE}/reducer/certs/reducer-cert.pem:/app/client/certs/client-cert.pem
    ports:
      - 8080:8080

  client2:
    environment:
      - GET_HOSTS_FROM=dns
      - CLIENT_NAME=${CLIENT_NAME_BASE}2
      - FEDN_MINIO_HOST=${FEDN_MINIO_HOST}
      - FEDN_MINIO_PORT=${FEDN_MINIO_PORT}
      - FEDN_MINIO_ACCESS_KEY=${FEDN_MINIO_ACCESS_KEY}
      - FEDN_MINIO_SECRET_KEY=${FEDN_MINIO_SECRET_KEY}
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/
    command: /bin/bash -c "fedn run client -d ${FEDN_REDUCER_HOST} -p ${FEDN_REDUCER_PORT} -n ${CLIENT_NAME_BASE}2 -t ${FEDN_ALLIANCE_ADMIN_AUTH_TOKEN}"
    volumes:
    #  - ./test/${EXAMPLE}/client:/app/client
      - ./test/${EXAMPLE}/data/data2:/app/data
      - ./test/${EXAMPLE}/reducer/certs/reducer-cert.pem:/app/client/certs/client-cert.pem    
  client3:
    environment:
      - GET_HOSTS_FROM=dns
      - CLIENT_NAME=${CLIENT_NAME_BASE}3
      - FEDN_MINIO_HOST=${FEDN_MINIO_HOST}
      - FEDN_MINIO_PORT=${FEDN_MINIO_PORT}
      - FEDN_MINIO_ACCESS_KEY=${FEDN_MINIO_ACCESS_KEY}
      - FEDN_MINIO_SECRET_KEY=${FEDN_MINIO_SECRET_KEY}
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/
    command: /bin/bash -c "fedn run client -d ${FEDN_REDUCER_HOST} -p ${FEDN_REDUCER_PORT} -n ${CLIENT_NAME_BASE}2 -t ${FEDN_ALLIANCE_ADMIN_AUTH_TOKEN}"
    volumes:
    #  - ./test/${EXAMPLE}/client:/app/client
      - ./test/${EXAMPLE}/data/data3:/app/data
      - ./test/${EXAMPLE}/reducer/certs/reducer-cert.pem:/app/client/certs/client-cert.pem

  client4:
    environment:
      - GET_HOSTS_FROM=dns
      - CLIENT_NAME=${CLIENT_NAME_BASE}4
      - FEDN_MINIO_HOST=${FEDN_MINIO_HOST}
      - FEDN_MINIO_PORT=${FEDN_MINIO_PORT}
      - FEDN_MINIO_ACCESS_KEY=${FEDN_MINIO_ACCESS_KEY}
      - FEDN_MINIO_SECRET_KEY=${FEDN_MINIO_SECRET_KEY}
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/
    command: /bin/bash -c "fedn run client -d ${FEDN_REDUCER_HOST} -p ${FEDN_REDUCER_PORT} -n ${CLIENT_NAME_BASE}2 -t ${FEDN_ALLIANCE_ADMIN_AUTH_TOKEN}"
    volumes:
    #  - ./test/${EXAMPLE}/client:/app/client
      - ./test/${EXAMPLE}/data/data4:/app/data
      - ./test/${EXAMPLE}/reducer/certs/reducer-cert.pem:/app/client/certs/client-cert.pem      
