version: '3.3'
services:
  client1:
    environment:
      - GET_HOSTS_FROM=dns
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/
    command: /bin/bash -c "fedn run client -in ./config/settings-client.yaml"
    volumes:
      - ./config:/app/config
      - ./test/${EXAMPLE}/data/data1:/app/data

  client2:
    environment:
      - GET_HOSTS_FROM=dns
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/
    command: /bin/bash -c "fedn run client -in ./config/settings-client.yaml"
    volumes:
      - ./config:/app/config
      - ./test/${EXAMPLE}/data/data2:/app/data

  client3:
    environment:
      - GET_HOSTS_FROM=dns
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/
    command: /bin/bash -c "fedn run client -in ./config/settings-client.yaml"
    volumes:
      - ./config:/app/config
      - ./test/${EXAMPLE}/data/data3:/app/data

  client4:
    environment:
      - GET_HOSTS_FROM=dns
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/
    command: /bin/bash -c "fedn run client -in ./config/settings-client.yaml"
    volumes:
      - ./config:/app/config
      - ./test/${EXAMPLE}/data/data1:/app/data

  client5:
    environment:
      - GET_HOSTS_FROM=dns
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/
    command: /bin/bash -c "fedn run client -in ./config/settings-client.yaml"
    volumes:
      - ./config:/app/config
      - ./test/${EXAMPLE}/data/data2:/app/data

  client6:
    environment:
      - GET_HOSTS_FROM=dns
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/
    command: /bin/bash -c "fedn run client -in ./config/settings-client.yaml"
    volumes:
      - ./config:/app/config
      - ./test/${EXAMPLE}/data/data3:/app/data

  client7:
    environment:
      - GET_HOSTS_FROM=dns
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/
    command: /bin/bash -c "fedn run client -in ./config/settings-client.yaml"
    volumes:
      - ./config:/app/config
      - ./test/${EXAMPLE}/data/data3:/app/data

  client8:
    environment:
      - GET_HOSTS_FROM=dns
    image: "scaleoutsystems/client:latest"
    build:
      context: .
      dockerfile: components/client/Dockerfile
    working_dir: /app/
    command: /bin/bash -c "fedn run client -in ./config/settings-client.yaml"
    volumes:
      - ./config:/app/config
      - ./test/${EXAMPLE}/data/data1:/app/data