# Compose schema version
version: '3.4'

# Overriding requirements

x-env: &defaults
  GET_HOSTS_FROM: dns
  FEDN_PACKAGE_EXTRACT_DIR: package

services:

  client1:
    extends:
      file: ${HOST_REPO_DIR:-.}/docker-compose.yaml
      service: client
    environment:
      <<: *defaults
      FEDN_DATA_PATH: /app/package/client/data/MedNIST
      FEDN_CLIENT_SETTINGS_PATH: /app/client_settings.yaml  
    deploy:
      replicas: 1
    volumes:
      - ${HOST_REPO_DIR:-.}/fedn:/app/fedn
      - ${HOST_REPO_DIR:-.}/examples/monai-2D-mednist/client_settings.yaml:/app/client_settings.yaml  

  client2:
    extends:
      file: ${HOST_REPO_DIR:-.}/docker-compose.yaml
      service: client
    environment:
      <<: *defaults
      FEDN_DATA_PATH: /app/package/client/data/MedNIST
    deploy:
      replicas: 1
    volumes:
      - ${HOST_REPO_DIR:-.}/fedn:/app/fedn
