# Compose schema version
version: '3.3'

# Overriding requirements
services:
  client:
    build:
      args:
        REQUIREMENTS: examples/async-simulation/requirements.txt
    deploy:
      replicas: 2
    volumes:
      - ${HOST_REPO_DIR:-.}/fedn:/app/fedn
      - ${HOST_REPO_DIR:-.}/examples/async-simulation/data:/var/data
      - /var/run/docker.sock:/var/run/docker.sock
