version: '3.3'

services:

  combiner:
    image: "scaleoutsystems/fedn-combiner:develop"
    environment:
      - PYTHONUNBUFFERED=0
      - GET_HOSTS_FROM=dns
    build:
      context: ${PWD}
      dockerfile: ${PWD}/components/base/Dockerfile
    working_dir: /app/client
    command: sh -c "sleep 5 && pip install -e /app/fedn/ && fedn run combiner --init=./config/settings-combiner.yaml"
    volumes:
      - ${PWD}/config:/app/client/config
      - ${PWD}/fedn:/app/fedn
    ports:
      - 12080:12080